<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <!-- Braucht HttpContext für die Auflösung des aufrufenden Benutzers. -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TennisTurnier.Application\TennisTurnier.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

</Project>
