// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisTurnier.Adapters.Persistence.Sqlite;

#nullable disable

namespace TennisTurnier.Adapters.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(TennisTurnierDbContext))]
    [Migration("20260728085955_InitialClubsAndSecurity")]
    partial class InitialClubsAndSecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.AvailabilityWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "DayOfWeek");

                    b.ToTable("AvailabilityWindows", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Clubs", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCenterCourt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Name")
                        .IsUnique();

                    b.ToTable("Courts", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.CourtBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "TennisTurnier.Domain.Clubs.CourtBlock.Period#TimeSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("End")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("EndsAt");

                            b1.Property<string>("Start")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("StartsAt");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.ToTable("CourtBlocks", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Security.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Scope", "TennisTurnier.Domain.Security.RoleAssignment.Scope#ResourceScope", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("ResourceId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeResourceId");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeType");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Security.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "SubjectId")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.AvailabilityWindow", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Clubs.Court", null)
                        .WithMany("Availability")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Court", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Clubs.Club", null)
                        .WithMany("Courts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.CourtBlock", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Clubs.Court", null)
                        .WithMany("Blocks")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Security.RoleAssignment", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Security.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Club", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Court", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
