// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisTurnier.Adapters.Persistence.Sqlite;

#nullable disable

namespace TennisTurnier.Adapters.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(TennisTurnierDbContext))]
    [Migration("20260818094519_Satzformat")]
    partial class Satzformat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TennisTurnier.Domain.Formats.FormatTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Definition");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("FormatTemplates", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Score")
                        .HasColumnType("TEXT")
                        .HasColumnName("Score");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Side1", "TennisTurnier.Domain.Matches.Match.Side1#MatchSide", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("EntryId")
                                .HasColumnType("TEXT")
                                .HasColumnName("Side1_EntryId");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("Side1_Origin");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Side2", "TennisTurnier.Domain.Matches.Match.Side2#MatchSide", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("EntryId")
                                .HasColumnType("TEXT")
                                .HasColumnName("Side2_EntryId");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("Side2_Origin");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("PhaseId", "Round", "Position");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Phases.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Ordinal")
                        .IsUnique();

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "TennisTurnier.Domain.Players.Player.Contact#PlayerContact", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly?>("DateOfBirth")
                                .HasColumnType("TEXT")
                                .HasColumnName("DateOfBirth");

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.PublicView.TournamentProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("TournamentId");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TournamentProjections", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Scheduling.CourtAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EarliestStart")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EstimatedDuration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceOnCourt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("CourtId", "SequenceOnCourt");

                    b.ToTable("CourtAssignments", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Security.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Scope", "TennisTurnier.Domain.Security.RoleAssignment.Scope#ResourceScope", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("ResourceId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeResourceId");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeType");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Security.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "SubjectId")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.CourtWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "TennisTurnier.Domain.Tournaments.CourtWindow.Period#TimeSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("End")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("To");

                            b1.Property<string>("Start")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("From");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("TournamentId", "CourtId");

                    b.ToTable("CourtWindows", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PlayerIds");

                    b.HasKey("Id");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT")
                        .HasColumnName("FormatSnapshot");

                    b.Property<Guid>("FormatTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchFormat")
                        .HasColumnType("TEXT")
                        .HasColumnName("MatchFormat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartsOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Venue", "TennisTurnier.Domain.Tournaments.Tournament.Venue#Venue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("VenueAddress");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("VenueCity");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("VenueName");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("TimeZoneId");
                        });

                    b.HasKey("Id");

                    b.HasIndex("StartsOn");

                    b.ToTable("Tournaments", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.TournamentCourt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCenterCourt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Name")
                        .IsUnique();

                    b.ToTable("TournamentCourts", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.TournamentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TournamentId", "ParticipantId");

                    b.ToTable("TournamentEntries", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Matches.Match", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Phases.Phase", null)
                        .WithMany("Matches")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Phases.Phase", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Tournaments.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Scheduling.CourtAssignment", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Tournaments.TournamentCourt", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisTurnier.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Security.RoleAssignment", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Security.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.CourtWindow", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Tournaments.TournamentCourt", null)
                        .WithMany("Windows")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.Tournament", b =>
                {
                    b.OwnsOne("TennisTurnier.Domain.Tournaments.RegistrationLink", "Registration", b1 =>
                        {
                            b1.Property<Guid>("TournamentId")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Capacity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("RegistrationCapacity");

                            b1.Property<string>("Deadline")
                                .HasColumnType("TEXT")
                                .HasColumnName("RegistrationDeadline");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT")
                                .HasColumnName("RegistrationToken");

                            b1.HasKey("TournamentId");

                            b1.HasIndex("Token")
                                .IsUnique();

                            b1.ToTable("Tournaments");

                            b1.WithOwner()
                                .HasForeignKey("TournamentId");
                        });

                    b.Navigation("Registration")
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.TournamentCourt", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Tournaments.Tournament", null)
                        .WithMany("Courts")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.TournamentEntry", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Tournaments.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisTurnier.Domain.Tournaments.Tournament", null)
                        .WithMany("Entries")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Phases.Phase", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.Tournament", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.TournamentCourt", b =>
                {
                    b.Navigation("Windows");
                });
#pragma warning restore 612, 618
        }
    }
}
