// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisTurnier.Adapters.Persistence.Sqlite;

#nullable disable

namespace TennisTurnier.Adapters.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(TennisTurnierDbContext))]
    [Migration("20260728111719_MatchesAndAssignments")]
    partial class MatchesAndAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.AvailabilityWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "DayOfWeek");

                    b.ToTable("AvailabilityWindows", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Clubs", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCenterCourt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Name")
                        .IsUnique();

                    b.ToTable("Courts", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.CourtBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "TennisTurnier.Domain.Clubs.CourtBlock.Period#TimeSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("End")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("EndsAt");

                            b1.Property<string>("Start")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("StartsAt");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.ToTable("CourtBlocks", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Formats.FormatTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Definition");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("FormatTemplates", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Score")
                        .HasColumnType("TEXT")
                        .HasColumnName("Score");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Side1", "TennisTurnier.Domain.Matches.Match.Side1#MatchSide", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("EntryId")
                                .HasColumnType("TEXT")
                                .HasColumnName("Side1_EntryId");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("Side1_Origin");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Side2", "TennisTurnier.Domain.Matches.Match.Side2#MatchSide", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("EntryId")
                                .HasColumnType("TEXT")
                                .HasColumnName("Side2_EntryId");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("Side2_Origin");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("PhaseId", "Round", "Position");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Phases.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Ordinal")
                        .IsUnique();

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "TennisTurnier.Domain.Players.Player.Contact#PlayerContact", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly?>("DateOfBirth")
                                .HasColumnType("TEXT")
                                .HasColumnName("DateOfBirth");

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Scheduling.CourtAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActualStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EarliestStart")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EstimatedDuration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceOnCourt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("CourtId", "SequenceOnCourt");

                    b.ToTable("CourtAssignments", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Security.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Scope", "TennisTurnier.Domain.Security.RoleAssignment.Scope#ResourceScope", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("ResourceId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeResourceId");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ScopeType");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Security.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "SubjectId")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PlayerIds");

                    b.HasKey("Id");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT")
                        .HasColumnName("FormatSnapshot");

                    b.Property<Guid>("FormatTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("ClubId", "StartsOn");

                    b.ToTable("Tournaments", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.TournamentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TournamentId", "ParticipantId");

                    b.ToTable("TournamentEntries", (string)null);
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.AvailabilityWindow", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Clubs.Court", null)
                        .WithMany("Availability")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Court", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Clubs.Club", null)
                        .WithMany("Courts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.CourtBlock", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Clubs.Court", null)
                        .WithMany("Blocks")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Matches.Match", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Phases.Phase", null)
                        .WithMany("Matches")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Phases.Phase", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Tournaments.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Scheduling.CourtAssignment", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Clubs.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisTurnier.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Security.RoleAssignment", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Security.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.Tournament", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Clubs.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.TournamentEntry", b =>
                {
                    b.HasOne("TennisTurnier.Domain.Tournaments.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TennisTurnier.Domain.Tournaments.Tournament", null)
                        .WithMany("Entries")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Club", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("TennisTurnier.Domain.Clubs.Court", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("TennisTurnier.Domain.Phases.Phase", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("TennisTurnier.Domain.Tournaments.Tournament", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
